---
- name: Install fleur dependencies
  become: true
  become_user: "{{ root_user }}"
  apt:
    name:
      - build-essential
      - gfortran
      - gcc
      - openmpi-bin
      - libopenmpi-dev
      - liblapack-dev
      - libblas-dev
      - binutils-gold
      - git
      - cmake
      - libxml2-dev
      - doxygen

- name: Get fleur source
  unarchive:
    src: "{{ fleur_url }}"
    dest: "{{ fleur_code_folder }}"
    remote_src: true

# note: this does not throw an error, even if configure fails...
- name: Configure fleur
  shell: FC=mpif90 ./configure.sh AUTO
  args:
    chdir: "{{ fleur_topdir }}"
    creates: "{{ fleur_topdir }}/build/Makefile"

- name: Make fleur executables
  command: "make"
  args:
    chdir: "{{ fleur_topdir }}/build"
    creates: "{{ fleur_topdir }}/build/fleur"
  register: fleur_make

- import_tasks: tests.yml
  when: fleur_make.changed and run_tests is defined and run_tests
